ext {
    springBootVersion = "4.0.2"
    springVersion = "7.0.5"
//    springBootVersion = "3.5.11"
//    springVersion = "6.2.16"

    lv = '2.25.3'

    ffconversion = 'cn.featherfly:featherfly-conversion:1.5.1'
    ffoffice = 'cn.featherfly:featherfly-data-office:0.2.0'

//    springdocui = 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
}
sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir 'src/main/java-api'
            srcDir 'src/main/java-api-impl'
        }
    }
}

dependencies {
    implementation ffcommon
    implementation ffconversion
    implementation ffoffice
    implementation 'cn.featherfly.common:common-functional:0.3.0'
    implementation 'cn.featherfly.common:common-spring:0.3.0'
//    implementation 'cn.featherfly.web:web-jakarta:1.4.0'
    implementation 'cn.featherfly:featherfly-web-springmvc:1.0.3'
    // spring boot
//    implementation "org.springframework:spring-webmvc:7.0.3'
//    implementation "org.springframework.boot:spring-boot-starter-web:3.5.10'
    implementation "org.springframework.boot:spring-boot-starter:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-configuration-processor:${springBootVersion}"
//    implementation "org.springframework.boot:spring-boot-devtools:${springBootVersion}"
    // spring
//    implementation "org.springframework:spring-expression:${springVersion}"
//    implementation "org.springframework:spring-core:${springVersion}"
//    implementation "org.springframework:spring-beans:${springVersion}"
//    implementation "org.springframework:spring-context:${springVersion}"
//    implementation "org.springframework:spring-context-support:${springVersion}"
//    implementation "org.springframework:spring-webmvc:${springVersion}"
//    implementation "org.springframework:spring-aop:${springVersion}"
    implementation "org.springframework:spring-tx:${springVersion}"

    //
    //    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'


    //    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
    implementation 'jakarta.validation:jakarta.validation-api:4.0.0-M1'

    // jackson
//    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.21'
//    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.0'
//    implementation 'tools.jackson.core:jackson-databind:3.0.4'

    // swagger
    implementation 'com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:4.5.0'

    // log4j
    implementation "org.apache.logging.log4j:log4j-slf4j-impl:${lv}"
    implementation "org.apache.logging.log4j:log4j-api:${lv}"
    implementation "org.apache.logging.log4j:log4j-core:${lv}"
    implementation "org.apache.logging.log4j:log4j-web:${lv}"
}


configurations {
    compile.transitive = true
    all*.exclude module: 'log4j'
    all*.exclude module: 'slf4j-log4j12'
    all*.exclude module: 'log4j-to-slf4j'
    all*.exclude module: 'pull-parser'
//        compile.exclude module: 'javax.el'
    all*.exclude module: 'logback-core'
    all*.exclude module: 'logback-classic'
    all*.exclude module: 'spring-boot-starter-logging'
    all*.exclude module: 'jbox-organization-impl'
    all*.exclude module: 'jbox-organization-admin-api'

//        all*.exclude module : 'spring-boot-starter-logging'
}

configurations.all {
    resolutionStrategy {
        // force certain versions of dependencies (including transitive)
        //  *append new forced modules:
        force ffconversion, ffoffice/*, springdocui*/
        //  *replace existing forced modules with new ones:
        forcedModules = [ffconversion, ffoffice/*, springdocui*/
        ]
    }
}