plugins {
    id 'org.jreleaser' version '1.22.0'
}

allprojects {
    apply from: rootDir.getAbsolutePath() +  '/gradle/java_base.gradle'
    apply from: rootDir.getAbsolutePath() +  '/gradle/maven_push.gradle'
    
    ext {
        ffcommon = "cn.featherfly.common:common-core:1.16.1"
    }   

    dependencies {
        api group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'
        //api group: 'cn.featherfly.common', name: 'common-api', version: '0.2.4'
        //api group: 'cn.featherfly.common', name: 'common-core', version: '1.8.19'		

        testImplementation group: 'org.testng', name: 'testng', version: '7.5.1'
        testImplementation group: 'com.google.inject', name: 'guice', version: '4.2.3'
        testImplementation 'org.slf4j:slf4j-log4j12:1.7.30'
        testImplementation 'log4j:log4j:1.2.17'
    }
}

//plugins {
//    id 'org.hidetake.swagger.generator' version '2.19.2'
//}

ext {
//    swagger = 'io.swagger.codegen.v3:swagger-codegen:3.0.76'
}

sourceSets {
    test {
        java {
            srcDir 'src/gen/java'
            srcDir 'src/gen/springmvc-v3'
            srcDir 'src/gen/android/java'
            srcDir 'src/gen/springclound/java-api'
            srcDir 'src/gen/springclound/java-client'
            srcDir 'src/gen/springclound/java-server'
        }
    }
}

dependencies {
    api ffcommon
    api 'cn.featherfly.common:common-functional:0.3.0'
    api 'cn.featherfly.conversion:conversion-codegen:0.1.0'
//    api swagger
    api 'io.swagger.codegen.v3:swagger-codegen-generators:1.0.62'
    // swagger command line
//    api 'io.swagger.codegen.v3:swagger-codegen-cli:3.0.76'

//    // swagger web ui
//    // implementation 'io.swagger.codegen.v3:swagger-generator:3.0.76'
//
//    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.0'
//    implementation 'com.squareup.okhttp3:okhttp:3.14.9'
//
//    implementation group: 'commons-io', name: 'commons-io', version: '2.16.1'
//    //implementation group: 'org.springframework', name: 'spring-webmvc', version: '6.1.8'
//    //implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '3.3.0'

//    compileOnly 'org.openapitools:openapi-generator-cli:7.19.0'


    testImplementation 'org.testng:testng:7.5.1'

    // test code gen
//    testImplementation "org.springframework:spring-webmvc:${springVersion}"
//    testImplementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    testImplementation 'javax.annotation:javax.annotation-api:1.3.2'
//    testImplementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    testImplementation 'tools.jackson.core:jackson-databind:3.0.4'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.21.0'
//    testImplementation 'jakarta.validation:jakarta.validation-api:3.1.1'


    // swaggerCodegen 'io.swagger:swagger-codegen-cli:2.4.41'             // Swagger Codegen V2
    // swaggerCodegen 'io.swagger.codegen.v3:swagger-codegen-cli:3.0.57'  // or Swagger Codegen V3
    // swaggerCodegen 'org.openapitools:openapi-generator-cli:3.3.4'     // or OpenAPI Generator
    // swaggerCodegen 'org.openapitools:openapi-generator-cli:7.6.0'     // or OpenAPI Generator
}

//swaggerSources {
//    order {
//        inputFile = file('api/order-api.yaml')
//        code {
//            language = 'spring'
//        }
//    }
//}