/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppVersionQueryDto } from './AppVersionQueryDto';
/**
 * 
 * @export
 * @interface AppCodeDto
 */
export interface AppCodeDto extends AppVersionQueryDto {
}
