/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * app基础对象
 * @export
 * @interface AppDto
 */
export interface AppDto {
    /**
     * 编码
     * @type {string}
     * @memberof AppDto
     */
    code?: string;
    /**
     * 描述
     * @type {string}
     * @memberof AppDto
     */
    descp?: string;
    /**
     * 名称
     * @type {string}
     * @memberof AppDto
     */
    name?: string;
}
