/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppDto } from './AppDto';
import { AppVersionQueryDto } from './AppVersionQueryDto';
/**
 * app查询对象
 * @export
 * @interface AppQueryDto
 */
export interface AppQueryDto extends AppDto {
    /**
     * 主键id
     * @type {number}
     * @memberof AppQueryDto
     */
    id?: number;
    /**
     * 
     * @type {AppVersionQueryDto}
     * @memberof AppQueryDto
     */
    appVersion?: AppVersionQueryDto;
    /**
     * 应用平台
     * @type {string}
     * @memberof AppQueryDto
     */
    platformName?: string;
}
