/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 版本修改对象
 * @export
 * @interface AppVersionUpdateDto
 */
export interface AppVersionUpdateDto {
    /**
     * 主键id
     * @type {number}
     * @memberof AppVersionUpdateDto
     */
    id?: number;
    /**
     * 描述
     * @type {string}
     * @memberof AppVersionUpdateDto
     */
    descp?: string;
}
