/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppVersionDto } from './AppVersionDto';
import { PlatformDto } from './PlatformDto';
/**
 * app保存对象
 * @export
 * @interface AppVersionSaveDto
 */
export interface AppVersionSaveDto extends AppVersionDto {
}
