/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlatformDto } from './PlatformDto';
/**
 * app版本基础对象
 * @export
 * @interface AppVersionDto
 */
export interface AppVersionDto {
    /**
     * 软件id
     * @type {number}
     * @memberof AppVersionDto
     */
    appId?: number;
    /**
     * 编码
     * @type {string}
     * @memberof AppVersionDto
     */
    versionCode?: string;
    /**
     * 描述
     * @type {string}
     * @memberof AppVersionDto
     */
    descp?: string;
    /**
     * 名称
     * @type {string}
     * @memberof AppVersionDto
     */
    url?: string;
    /**
     * 上传文件hash
     * @type {string}
     * @memberof AppVersionDto
     */
    storeKey?: string;
    /**
     * 发行日期
     * @type {Date}
     * @memberof AppVersionDto
     */
    releaseDate?: Date;
    /**
     * 版本号
     * @type {number}
     * @memberof AppVersionDto
     */
    version?: number;
    /**
     * 
     * @type {PlatformDto}
     * @memberof AppVersionDto
     */
    platforms?: PlatformDto;
}
