/* tslint:disable */
/* eslint-disable */
/**
 * app
 * app有关的API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zhongj@cdzkdc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 平台类型返回对象
 * @export
 * @interface PlatformDto
 */
export interface PlatformDto {
    /**
     * 主键id
     * @type {number}
     * @memberof PlatformDto
     */
    id?: number;
    /**
     * 名称
     * @type {string}
     * @memberof PlatformDto
     */
    name?: string;
    /**
     * 
     * @type {Array&lt;PlatformDto&gt;}
     * @memberof PlatformDto
     */
    platform?: Array<PlatformDto>;
}
